### PR TITLE
Added capability to specify more than two areas of actions both on left ...

### PR DESCRIPTION
**Pull request by wedkarz**
...and right side.

### CODE REVIEW

**Comment by Dromaguirre** [comment]
Hi Artur!

Thanks a lot for being interested in contributing to this project.

There has already been [__a version of PDGestureTableView__](https://github.com/Dromaguirre/PDGestureTableView/tree/151ef8863d24aedf21a0d5f813011e0ff6c6c08d) where more than 2 actions per side could be specified, but I got to the conclusion that it's just inconvenient for UX. The idea of having 2 actions is nice because of its spontaneity when it comes to doing an action or another (short/long swipe). Including more than 2 actions requires swipes to be carefully performed in order not to perform an undesired action.

I'd like to know your opinion on this.

**Comment by wedkarz** [comment]
Here as you see I have attached example for left swipe with 5 actions. And this is rather one action but in 5 states. Imagine that you'd like to rate something with stars (1-5). Having multiple actions on left/right side allows this. Of course you can still specify two actions. I don't see that two action approach complicates developer experience. I rather boosts possibilities.

**Comment by Dromaguirre** [comment]
@wedkarz I hadn't thought about it that way. There you go :)

**Comment by Dromaguirre** [comment]
@wedkarz if you have some time, please check out #15 where I explain what the future of this library will be like. Just so you know, I'll of course include this feature in `DRCellSwipeGestureRecognizer`.

**Comment by wedkarz** [comment]
Sure, I'll have a look, thanks!

**Pull request merged**
